# Generated by Django 2.0.4 on 2018-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=50, unique=True)),
                ('hotelnumber', models.IntegerField()),
                ('hoteladdress', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('itemdescription', models.CharField(max_length=200)),
            ],
        ),
    ]
