# Generated by Django 2.0.4 on 2018-04-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_hotels_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
