# Generated by Django 2.0.4 on 2018-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotelimage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
