# Generated by Django 2.0.4 on 2018-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_hotels_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
