# Generated by Django 2.0.4 on 2018-04-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_items_itemamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardvalidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=50)),
            ],
        ),
    ]
