# Generated by Django 2.0.4 on 2018-04-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_cardvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardvalidation',
            name='cardnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardvalidation',
            name='cvv',
            field=models.IntegerField(default=0),
        ),
    ]
